version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@35.175.203.152 \
            "echo Start deploy && \
            cd ~/sachin-app && \
            git pull origin master && \ 
            sudo docker compose up --build -d && \
            echo Deploy end"
workflows:
  version: 2
  deploy_ec2:
    jobs:
      - build
